[package]
name = "lrdf"
version = "0.1.0"
authors = ["Andreas Hauser <Andreas.Hauser@LMU.de>"]
edition = "2018"

[lib]
name = "lrdf"
crate-type = ["cdylib"]

[dependencies]
bio = "*"
chrono = "*"
permutation = "*"

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]
