[package]
name = "lrdf"
version = "0.1.0"
authors = ["Andreas Hauser <Andreas.Hauser@LMU.de>"]
edition = "2021"

[lib]
name = "lrdf"
crate-type = ["cdylib","lib"]

[[bin]]
name = "lrdf"

[dependencies]
bio = "*"
chrono = "*"
permutation = "*"
structopt = "*"

[workspace]
members = [ "lrdfpy" ]
