[package]
name = "lrdf"
version = "0.1.0"
authors = ["Andreas Hauser <Andreas.Hauser@LMU.de>"]
edition = "2018"

[lib]
name = "lrdf"
crate-type = ["cdylib","lib"]

[dependencies]
bio = "*"
chrono = "*"
permutation = "*"

[workspace]
members = [ "lrdfpy" ]
